on:
    push:
        branches:
        - main

jobs:
  db_cicd:
    name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Konek ke server..."
            if [ ! -d "Unch" ]; then
                echo "Folder Unch tidak ada, membuat folder..."
                mkdir Unch
            fi
            cd Unch
            

            if [ -d "git"]; then
                echo "Folder git ada, melakukan pull..."
                git remote set-url origin https://${{ secrets.GIT_USERNAME }}
                :${ secrets.SERVER_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/CICD_MKEPL.git
                git pull origin main
            else
                echo "Folder git tidak ada, melakukan clone..."
                git clone https://${{ secrets.GIT_USERNAME }}
                :${{ secrets.SERVER_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/CICD_MKEPL.git
            fi

