on:
    push:
        branches:
        - main

jobs:
  db_cicd:
    name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Konek ke server..."
            if [ ! -d "Unch" ]; then
                echo "Folder Unch tidak ada, membuat folder..."
                mkdir Unch
            fi

            cd Unch
            
            echo "docker compse down if running..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker compose down

            echo "docker compose up..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker compose up -d
            