name : CICD_DATABASE_Dev_to_Prod
on:
  push:
    branches:
      - main

jobs:
  - job: checkout_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1 
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${ secrets.SERVER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "nge print echo SSH Connection Successful"
